spring:
  application:
    name: GatewayService
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: gateway-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.eventmanager.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}

server:
  port: 8080

app:
  keycloak:
    server-url: ${KEYCLOAK_URL}
    realm: ${KEYCLOAK_REALM}
    client-id: ${GATEWAY_CLIENT_ID}
    client-secret: ${GATEWAY_CLIENT_SECRET}
    core-url: ${CORE_SERVICE_URL:http://localhost:8081}